CLASS zcl_lab_31_org_france_ag2 DEFINITION
  PUBLIC
  INHERITING FROM zcl_lab_29_organization_ag2
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_location REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_31_org_france_ag2 IMPLEMENTATION.
  METHOD get_location.

  rv_location = 'ORGANIZATION FRANCE'.

  ENDMETHOD.

ENDCLASS.
