CLASS zcl_lab_29_organization_ag2 DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS GET_LOCATION ABSTRACT RETURNING VALUE(rv_Location) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_29_organization_ag2 IMPLEMENTATION.


ENDCLASS.
