CLASS zcl_excel_ag02 DEFINITION INHERITING FROM zcl_document_ag02
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_excel_ag02 IMPLEMENTATION.
ENDCLASS.
