CLASS zcl_lab_12_linux_ag02 DEFINITION INHERITING FROM zcl_lab_11_system_ag02
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS zcl_lab_12_linux_ag02 IMPLEMENTATION.
ENDCLASS.
