CLASS zcl_lab_30_org_germany_ag2 DEFINITION INHERITING FROM zcl_lab_29_organization_ag2
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_location REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_30_org_germany_ag2 IMPLEMENTATION.
  METHOD get_location.

 rv_location = 'ORGANIZATION GERMANY'.

  ENDMETHOD.

ENDCLASS.
