CLASS zcl_lab_39_budget_ag02 DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS get_budget ABSTRACT RETURNING VALUE(rv_budget) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_39_budget_ag02 IMPLEMENTATION.
ENDCLASS.
